#!/bin/sh
###################
# git-hist v1.0.0
#
# @author RuneImp <runeimp@gmail.com>
# @licenses http://opensource.org/licenses/MIT
#
###
# ChangeLog
# ---------
# 2015-07-15  1.0.0       Initial script creation
#

if [ $# -eq 0 ]; then
	echo "You must specify the number of commits to include in the history graph" 1>&2
	exit 1
else
	git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short -$1
fi
